-- MySQL Script generated by MySQL Workbench
-- Mon May 30 16:33:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartoes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valorTotal` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carteira` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carteira` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `cartoes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carteira_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_carteira_cartoes1_idx` (`cartoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_carteira_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_cartoes1`
    FOREIGN KEY (`cartoes_id`)
    REFERENCES `mydb`.`cartoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operacoes` (
  `id` INT NOT NULL,
  `desc` VARCHAR(45) NULL,
  `dataTransacao` DATETIME(6) NULL,
  `valorOperacao` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartoes_has_operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartoes_has_operacoes` (
  `cartoes_id` INT NOT NULL,
  `operacoes_id` INT NOT NULL,
  PRIMARY KEY (`cartoes_id`, `operacoes_id`),
  INDEX `fk_cartoes_has_operacoes_operacoes1_idx` (`operacoes_id` ASC) VISIBLE,
  INDEX `fk_cartoes_has_operacoes_cartoes1_idx` (`cartoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_cartoes_has_operacoes_cartoes1`
    FOREIGN KEY (`cartoes_id`)
    REFERENCES `mydb`.`cartoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartoes_has_operacoes_operacoes1`
    FOREIGN KEY (`operacoes_id`)
    REFERENCES `mydb`.`operacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO usuario VALUES
(1,"Gabriel", 12345678900, "gabriel@gmail.com", "12345678"),
(2,"Alan", 09378293905, "alan@gmail.com", "12345678");

INSERT INTO cartoes VALUES 
(1,"visa",350),
(2,"master", 1000);

INSERT INTO carteira VALUES 
(1,"Principal",1,1),
(2,"Principal",2,2);